<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-16T23:43:11 EET" name="Default suite" finished-at="2025-07-16T23:43:45 EET" duration-ms="34589">
    <groups>
    </groups>
    <test started-at="2025-07-16T23:43:11 EET" name="Default test" finished-at="2025-07-16T23:43:45 EET" duration-ms="34589">
      <class name="AutomationTestCases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:AutomationTestCases@65fe9e33]" started-at="2025-07-16T23:43:11 EET" name="mySetup" finished-at="2025-07-16T23:43:15 EET" duration-ms="4755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="Signup()[pri:1, instance:AutomationTestCases@65fe9e33]" started-at="2025-07-16T23:43:15 EET" name="Signup" finished-at="2025-07-16T23:43:30 EET" duration-ms="14691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signup -->
        <test-method signature="Logout()[pri:2, instance:AutomationTestCases@65fe9e33]" started-at="2025-07-16T23:43:30 EET" name="Logout" finished-at="2025-07-16T23:43:35 EET" duration-ms="4506" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[this is to check that the user has been logged out expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: this is to check that the user has been logged out expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1079)
at org.testng.Assert.assertEquals(Assert.java:1043)
at AutomationTestCases.Logout(AutomationTestCases.java:159)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method signature="Login()[pri:3, instance:AutomationTestCases@65fe9e33]" started-at="2025-07-16T23:43:35 EET" name="Login" finished-at="2025-07-16T23:43:37 EET" duration-ms="2402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="AddtoCart()[pri:4, instance:AutomationTestCases@65fe9e33]" started-at="2025-07-16T23:43:37 EET" name="AddtoCart" finished-at="2025-07-16T23:43:45 EET" duration-ms="8156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddtoCart -->
      </class> <!-- AutomationTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
